### PR TITLE
Feature dininghall

### PR DESCRIPTION
**Pull request by ylkao**
Dining landing page: 
- page is vertically scroll-able instead of having horizontally scroll-able cards
- made dining hall and cafe sections collapsible: both can be open at the same time but both cannot be closed at the same time. added up/down arrows to the label, too.
- displays hours if open (couldn't display next opening hours if closed because they were null)
- aligns name, open status, and hours to the right of the image
image
image

### CODE REVIEW

**Comment by rustielin** [comment]
@ylkao Couple things need fixing and some recommendations:
* progress bar missing when loading. check your logic here for when you show/hide and also check what exists on screen at a given time and the relative ordering/layer
* formatting issue with your cards in `food_place.xml`. Attaching image below. I'd recommend nesting linear layouts (vs relative layout), and putting the open/closing times on their own line
dining

**Comment by ylkao** [comment]
Fixes:
-Dining hall and cafe sections are now both collapsible
-Formatting issue with times on food place should be fixed, but I might also have bad eyesight
image
image
image

**Comment by rustielin** [comment]
@ylkao formatting of cards is still broken for smaller devices. recommend just putting the hours below `open`

**Comment by ylkao** [comment]
Moved hours under open status
image

**Pull request merged**
